import os

Import("env")

# Bake lib/mock-arduino/script.txt into the firmware as a generated header so
# the scripted-interactions build (grandcentral_m4_glow_scripted) replays the
# exact PIR sequence the desktop mock plays, looping forever on the real
# sculpture. The header lands in $BUILD_DIR/generated and is only rewritten
# when its content changes, so an unchanged script.txt doesn't force a
# recompile every build.

SCRIPT_RELATIVE_PATH = os.path.join("lib", "mock-arduino", "script.txt")
NUMBER_OF_PANELS = 20

script_path = os.path.join(env.subst("$PROJECT_DIR"), SCRIPT_RELATIVE_PATH)

entries = []
with open(script_path) as script_file:
    for line_number, raw_line in enumerate(script_file, 1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise SystemExit("embed_mock_script: %s:%d: expected '<iteration> <pirs>'"
                             % (SCRIPT_RELATIVE_PATH, line_number))
        if len(parts[1]) != NUMBER_OF_PANELS:
            raise SystemExit("embed_mock_script: %s:%d: expected %d PIR digits, got %d"
                             % (SCRIPT_RELATIVE_PATH, line_number,
                                NUMBER_OF_PANELS, len(parts[1])))
        entries.append((int(parts[0]), parts[1]))

if not entries:
    raise SystemExit("embed_mock_script: %s has no entries" % SCRIPT_RELATIVE_PATH)

entries.sort(key=lambda entry: entry[0])

header_lines = [
    "// Generated by scripts/embed_mock_script.py from %s." % SCRIPT_RELATIVE_PATH,
    "// Do not edit; rebuilding grandcentral_m4_glow_scripted regenerates it.",
    "#pragma once",
    "",
    "static const int MOCK_SCRIPT_ENTRY_COUNT = %d;" % len(entries),
    "static const int MOCK_SCRIPT_LAST_ITERATION = %d;" % entries[-1][0],
    "static const int MOCK_SCRIPT_ITERATIONS[MOCK_SCRIPT_ENTRY_COUNT] = {",
]
header_lines.append("    " + ", ".join(str(iteration) for iteration, pirs in entries))
header_lines.append("};")
header_lines.append("static const char* const MOCK_SCRIPT_PIRS[MOCK_SCRIPT_ENTRY_COUNT] = {")
for iteration, pirs in entries:
    header_lines.append('    "%s",' % pirs)
header_lines.append("};")
header_content = "\n".join(header_lines) + "\n"

generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated_dir, exist_ok=True)
header_path = os.path.join(generated_dir, "MockScriptData.h")

existing_content = None
if os.path.exists(header_path):
    with open(header_path) as header_file:
        existing_content = header_file.read()
if existing_content != header_content:
    with open(header_path, "w") as header_file:
        header_file.write(header_content)

env.Append(CPPPATH=[generated_dir])
print("embed_mock_script: %d entries, last iteration %d"
      % (len(entries), entries[-1][0]))
